[package]
name = "pwdmgr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
rpassword = "7.0"
aes-gcm = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
base64 = "0.22.1"
sha_256 = "1.0.1"
sha2 = "0.10.9"
